---
title: "Repository Watch"
author: "Emil Hvitfeldt"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
params:
   github_token: !r gh::gh_token()
---

```{r setup, include=FALSE}
library(flexdashboard)
library(reactable)
library(tidyverse)
library(ymlthis)
library(glue)
library(gh)
```

Repositories
=======================================================================

```{r}
me <- "EmilHvitfeldt"
tm <- "Tidymodels"

repos <- tribble(
  ~owner, ~name,             ~org,
  me, "tilemapr",            FALSE,
  me, "ggtetris",            FALSE,
  me, "cookiemonster",       FALSE,
  me, "offensiveR",          FALSE,
  me, "tripleblind",         FALSE,
  me, "horus",               FALSE,
  me, "walmartAPI",          FALSE,
  me, "recap",               FALSE,
  me, "hcandersenr",         FALSE,
  me, "ehlib",               FALSE,
  me, "ggshapes",            FALSE,
  me, "quickpalette",        FALSE,
  me, "miscpalettes",        FALSE,
  me, "ggclipped",           FALSE,
  me, "ggshuffle",           FALSE,
  me, "paletteer",           FALSE,
  me, "gganonymize",         FALSE,
  me, "unitscales",          FALSE,
  me, "textdata",            FALSE,
  me, "ggpage",              FALSE,
  me, "glyphextra",          FALSE,
  me, "ElizabethWarrenMeme", FALSE,
  me, "prismatic",           FALSE,
  tm, "textrecipes",         TRUE,
  tm, "themis",              TRUE
)
```

```{r}
r_cmd_check_svg <- function(x) {
  if (x$total_count == 0) {
    return(NA)
  }
  
  workflow_names <- map_chr(x$workflows,  "name")
  
  if(!any(workflow_names == "R-CMD-check")) {
    return(NA)
  }
  
  x$workflows[workflow_names == "R-CMD-check"][[1]]$badge_url
}

r_cmd_check_svg_to_text <- function(x) {
  if (is.na(x)) {
      return("missing")
  }
      
  read_lines(x) %>%
    str_detect("passing") %>%
    any() %>%
    if_else("passing", "failing")
}
```

```{r}
r_cmd_check_versions <- function(x) {
  if (x$total_count == 0) {
    return("")
  }
  
  workflow_names <- map_chr(x$workflows,  "name")
  
  if(!any(workflow_names == "R-CMD-check")) {
    return("")
  }
  
  yaml <- x$workflows[workflow_names == "R-CMD-check"][[1]]$html_url %>%
    str_replace("https://github.com/", "https://raw.githubusercontent.com/") %>%
    str_remove("blob/") %>%
    read_toml()
  
  map_chr(yaml$jobs$`R-CMD-check`$strategy$matrix$config, "r") %>%
    sort() %>%
    unique() %>%
    paste(collapse = ", ")
}
```

```{r}
check_readme_bagdes <- function(x) {
  all_lines <- read_lines(x$download_url)
  start <- which(all_lines == "<!-- badges: start -->")
  end <- which(all_lines == "<!-- badges: end -->")
  
  if (!(length(start) == 1 && length(end) == 1)) {
    return(tibble(`bagde r_cmd_check` = FALSE,
                  `bagde codecov` = FALSE,
                  `bagde cran_version` = FALSE,
                  `bagde downloads` = FALSE,
                  `bagde lifecycle` = FALSE,
                  `bagde DOI` = FALSE
                  ))
  }
bagdes <- all_lines[seq(start + 1, end - 1)] %>%
  str_c(collapse = "") %>%
  str_split("\\[!\\[") %>%
  .[[1]] %>%
  str_remove_all("\\].*")

tibble(`bagde r_cmd_check` = "R buildstatus" %in% bagdes,
       `bagde codecov` = "Codecov testcoverage" %in% bagdes,
       `bagde cran_version` = "CRANstatus" %in% bagdes,
       `bagde downloads` = "Downloads" %in% bagdes,
       `bagde lifecycle` = any(str_detect(bagdes, "Lifecycle")),
       `bagde DOI` = "DOI" %in% bagdes
       )
}
```

```{r}
logical_style <- function(value) {
  value <- if_else(value, "yes", "no")
      class <- paste0("tag status-", value)
      htmltools::div(class = class, value)
  }
```


```{r}
github_actions <- map2(repos$owner, repos$name, 
                       ~ gh("GET /repos/:owner/:repo/actions/workflows", 
                            owner = .x, repo = .y, .token = params$github_token))


readme_bagde_status <- map2(repos$owner, repos$name,
                       ~ gh("GET /repos/:owner/:repo/readme", 
                            owner = .x, repo = .y, , .token = params$github_token)) %>%
  map_dfr(check_readme_bagdes)

table_data <- repos %>%
  mutate(`R CMD check` = map_chr(github_actions, r_cmd_check_svg),
         `R CMD check` = map_chr(`R CMD check`, r_cmd_check_svg_to_text),
         `Versions` = map_chr(github_actions, r_cmd_check_versions)) %>%
  bind_cols(readme_bagde_status)

table_data %>%
  select(-org, -owner) %>% 
  reactable::reactable(
    columns = list(
    `R CMD check` = colDef(cell = function(value) {
      class <- paste0("tag status-", value)
      htmltools::div(class = class, value)
  }),
  `bagde codecov` = colDef(cell = logical_style, name = "CodeCov"),
  `bagde r_cmd_check` = colDef(cell = logical_style, name = "C CMD check"),
  `bagde cran_version` = colDef(cell = logical_style, name = "CRAN version"),
  `bagde downloads` = colDef(cell = logical_style, name = "Downloads"),
  `bagde lifecycle` = colDef(cell = logical_style, name = "Lifecycle"),
  `bagde DOI` = colDef(cell = logical_style, name = "DOI"),
  name = colDef(name = "Name")
  ),
  columnGroups = list(
    colGroup(name = "Bagdes", columns = c("bagde r_cmd_check", "bagde codecov", "bagde cran_version", 
"bagde downloads", "bagde lifecycle", "bagde DOI"))
  )
  )

```

```{css}
.tag {
  display: inline-block;
  padding: 2px 12px;
  border-radius: 10px;
  font-weight: 600;
  font-size: 12px;
}

.status-passing {
  background: hsl(116, 60%, 90%);
  color: hsl(116, 30%, 25%);
}

.status-missing {
  background: hsl(230, 70%, 90%);
  color: hsl(230, 45%, 30%);
}

.status-failing {
  background: hsl(350, 70%, 90%);
  color: hsl(350, 45%, 30%);
}


.status-yes {
  background: hsl(116, 60%, 90%);
  color: hsl(116, 30%, 25%);
}

.status-no {
  background: hsl(350, 70%, 90%);
  color: hsl(350, 45%, 30%);
}
```

Metrics
=======================================================================

```{r}
monthly_downloads <- cranlogs::cran_downloads(repos$name, "last-month")
alltime_downloads <- cranlogs::cran_downloads(repos$name, from = "2012-10-10")
```
